# Generated by Django 4.1.3 on 2022-12-05 10:09

import django.core.validators
from django.db import migrations, models
import priorart.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriorArtSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPR_prior_art_invention_title', models.CharField(max_length=500)),
                ('IPR_prior_art_applicant_name', models.CharField(max_length=200)),
                ('IPR_prior_art_applicant_name_others', models.CharField(blank=True, max_length=200, null=True)),
                ('IPR_prior_art_inventor_name', models.CharField(max_length=250)),
                ('IPR_prior_art_inventor_name_others', models.CharField(blank=True, max_length=250, null=True)),
                ('IPR_prior_art_Invention_description', models.TextField(max_length=8500)),
                ('IPR_prior_art_keywords', models.CharField(max_length=200)),
                ('IPR_prior_art_from_user_email', models.CharField(max_length=150)),
                ('IPR_prior_art_date_received', models.DateTimeField(auto_now_add=True, null=True)),
                ('IPR_prior_art_date_replied', models.DateTimeField(blank=True, null=True, validators=[priorart.models.validate_prior_art_date])),
                ('IPR_prior_art_status', models.CharField(choices=[('Inprocess', 'Inprocess'), ('Completed', 'Completed')], default='Inprocess', max_length=30)),
                ('IPR_prior_art_replied_comments', models.TextField(max_length=8500)),
                ('IPR_prior_art_reply_doc_name', models.FileField(blank=True, null=True, upload_to='documents/reply/')),
                ('IPR_prior_art_uploaded_doc_name', models.FileField(upload_to='documents/upload/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])])),
            ],
        ),
    ]
